version: "3.1"
services:
# TODO: rework
#  nginx:
#    build: nginx/
#    ports:
#      - "80:80"
  server:
    build: backend/
    ports:
      - "8080:8080"
  client:
    build: web/
    ports:
      - "3000:3000"
